---
# tasks file for gluster-x509

- name: install openssl
  import_tasks: install_openssl_package.yml
  when: not gluster_assume_openssl_package_installed

- name: Enable secure access
  import_tasks: touch_secure_access.yml
  when: gluster_var_lib_glusterd_secure_access

- name: Generating Diffie Helmann Parameters (may take a while) 
  command: "openssl dhparam -out {{ gluster_x509_dh_param_path | quote }} {{gluster_x509_dh_param_bits | quote}}"
  args:
    creates: "{{ gluster_x509_dh_param_path }}"    # don't do it again if present
  when: gluster_x509_dh_param_generate          # do it this is true

- name: Generate RSA private key with
  command: "openssl genrsa -out {{ gluster_x509_private_key_path | quote}} {{ gluster_x509_private_key_bits | quote}}"
  args:
    creates: "{{ gluster_x509_private_key_path }}"

- name: Generate Certificate Request
  command: "openssl req -new -key {{ gluster_x509_private_key_path}} -out {{ gluster_x509_cert_request_path }} -subj {{ gluster_x509_certificate_subject }}"
  args:
    creates: "{{ gluster_x509_certificate_path }}"
# to so dont make cert request if cert is there / above is not true but ... lets see if -\"/CN={{ ansible_hostname }}\"
# it is a reasonable workaround
#  when:  when there is no certificate, when a certificate is old, about to expire, forced

- name: Generate self signed certificate
  command: "openssl x509 -signkey {{ gluster_x509_private_key_path }} -in {{ gluster_x509_cert_request_path }} -req -out {{ gluster_x509_certificate_path}} -days {{ gluster_x509_certificate_days }}"
  args:
    creates: "{{ gluster_x509_certificate_path }}"
  register: generate_self_signed_cert
  when:  gluster_x509_signing == "self_signed"

- debug: 
    msg: "STDOUT: {{ generate_self_signed_cert.stdout }}"
  when: generate_self_signed_cert.stdout is defined
- debug: 
    msg: "STDERR: {{ generate_self_signed_cert.stderr }}"
  when: generate_self_signed_cert.stderr is defined

- name: Fetch certificate request to sign with local certificate request
  fetch:
    src: "{{ gluster_x509_cert_request_path }}"
    dest: "{{ gluster_x509_local_ca_requests_dir }}/{{ ansible_hostname }}_.csr"
    flat: True
  when:  gluster_x509_signing == "local_ca"

- name: Sign certificate using local CA
  import_tasks: sign_certificate_with_local_ca.yml
  when:  gluster_x509_signing == "local_ca"

- name: Check certificate expiry
  shell: echo $(( ($(date +%s --date="$( openssl x509 -in  {{ gluster_x509_certificate_path }} -enddate -noout |sed 's/notAfter=//')") - $(date +%s)) / 86400 ))
  register: certificate_days_left

- debug: 
    msg: "certificate in {{ ansible_host }} expires in {{certificate_days_left.stdout}} days {{ ansible_host }}"

- debug: 
    msg: "certificate has expired! or expires today!!!"
  when: certificate_days_left.stdout|int <= 0

- debug: 
    msg: "certificate will expire soon!!"
  when: 
    - certificate_days_left.stdout|int > 0 
    - certificate_days_left.stdout|int < 40

- name: Self-signed certificate bundle CA update
  import_tasks: update-self-signed-cert-bundle-ca.yml
  when: gluster_x509_signing == "self_signed"

- name: copy CA file to host
  copy:
    src:  "{{ gluster_x509_local_ca_certificate }}"
    dest: "{{ gluster_x509_ca_bundle_path }}" 
  when: gluster_x509_signing == "local_ca"
