#---
# sign_certificate_with_local_ca.yml
#
# 

- name: Signing with local CA
  no_log: "{{ gluster_x509_no_log_passwords | bool }}"
  command: "openssl ca {{ gluster_x509_local_ca_config_option }} -batch -create_serial -out {{ gluster_x509_local_ca_newcerts_dir }}/{{ ansible_hostname }}_.pem -passin pass:{{ gluster_x509_local_ca_passphrase }} -infiles {{ gluster_x509_local_ca_requests_dir }}/{{ ansible_hostname }}_.csr"
  delegate_to: localhost
  register: sign_result

# TODO: signing policy option?
# TODO: better test for failure to sign
#- pause:
#    prompt: "...enter to continue"
#  when: sign_result.failed

- name: Copy the locally signed certficate to the host
  copy:
    src: "{{ gluster_x509_local_ca_newcerts_dir }}/{{ ansible_hostname }}_.pem"
    dest: "{{ gluster_x509_certificate_path }}"
